## Basic Theme Info
name: WVU Brand Patterns
description: This is the WVU Brand Patterns theme built for CleanSlate. Originally authored by Adam Glenn.

## Attributes, Data and Variables
custom_site_attributes:
  # For Google Search Console
  - google_site_verification
  - masthead_color
  - twitter_handle
  - facebook_url
  - instagram_url
  - linkedin_url
  - rss_url
  - youtube_url
  - twitter_widget_id
  - calendar_feed
  - jquery_defer
  - nav
  - default_content_01
  - default_content_02
  - default_content_03

## Template Config
# Specify which templates show up by default when creating a page
default_templates:
  content: backpage
  blog: blog_index
  article: blog_article
  error: backpage

## Optimizations
css:
  # Turn CSS compression on/off.
  compress: true
js:
  # Turn JavaScript compression and mangling on/off
  compress: true
  mangle: true
